### ISSUE TITLE
Litmus pre-launch checklist

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/research-force#110]
### Deadline 23 Jan

The originally completed polkadot parachain checklist [can be found here](https://github.com/litentry/research-force/issues/23) for reference.

In this checklist only exclusive tasks for kusama-parachain are listed.
In each category the task is ordered by importance: **higher priority tasks are listed first**.

## Genesis ~1 Pt @qiuhaiguo 
to be finalized by **management board**
- [x] #112
- [x] #113
- [x] define address format ([SS58Prefix](https://github.com/paritytech/ss58-registry/blob/main/ss58-registry.json) - can be done by dev team) - decided on 131
- [x] define parachain ID (reserve ID on polkadot-JS)
- [x] double check sudo and collator accounts (same as polkadot?)
- [x] double check council/tech-committee (low prior, can be changed later)

## Runtime ~4 Pts 
to be finalized by **dev team**
- [x] https://github.com/litentry/litentry-parachain/issues/298
       (include chain-spec separation, structure changes, most time-consuming part) @h4n0 
- [x] double check the runtime parameters and binding @wangminqi 
- [x] https://github.com/litentry/litentry-parachain/issues/306

## Devops
to be finalized by **devops team**
- [x] generate 3 session keys for collators
- [x] define domain name for bootnodes
- [x] generate p2p keys for bootnodes
- [x] deployment scripts adjustment (kusama/polkadot)
- [x] https://github.com/litentry/litentry-parachain/issues/289
- [x] https://github.com/litentry/litentry-parachain/issues/295
- [x] new servers with enough HDD: 3 collators + 2 rpc-nodes (can be done after crowdloan)

## Tests
- [x] deployment test on staging
- [x] wasm test on staging (block authoring, sudo operations, runtime upgrade)
- [x] make sure it doesn't break the submitted polkadot wasm

Rough estimation: **14 man-days**, on condition that:
- no new tokens are being issued
- no new pallets are being integrated into the initial wasm

**Comment by qiuhaiguo** [comment]
keep sudo, collator and council/tech-committee accounts the same as Polkadot.

**Comment by qiuhaiguo** [comment]
Kusama Parachain Id: 2106 (via account: CsCrPSvLBPSSxJuQmDr18FFZPAQCtKVmsMu9YRTe5VToGeq)

**Comment by wangminqi** [comment]
https://www.notion.so/litentry/Parachain-Parameters-Difference-on-Kusama-Polkadot-Eco-system-73bfe306411143ce9f018542bced8fb4

This is for a general comparison of pallet parameter among kusama/polkadot.

**Comment by Kailai-Wang** [comment]
Litmus wasm released:  https://github.com/litentry/litentry-parachain/releases/tag/v0.9.2

RPC endpoint: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.litmus-parachain.litentry.io#/explorer

**Comment by Kailai-Wang** [comment]
Tested on staging:

- [x] sudo -> `setBlance` -> should be OK
- [x] sudo -> `forceTransfer` -> should be OK
- [x] Collator -> `balance.transfer`  -> should fail (callFiltered)
- [x] Normal account -> extrinsicFilter -> `setMode` -> should fail (bad origin)
- [x] sudo -> extrinsicFilter  -> `setMode (Test)` -> should be OK
- [x] Collator -> `balance.transfer` -> should be OK
- [x] sudo -> extrinsicFilter  -> `blockExtrinsics (Balances, )` -> should be OK
- [x] Normal account -> `balance.transfer` -> should fail (callFiltered)
- [x] sudo -> extrinsicFilter  -> `unblockExtrinsics (Balances, )` -> should be OK
- [x] sudo -> runtime upgrade -> should be OK

**Comment by Kailai-Wang** [comment]
Closed as the wasm was submitted.
