### ISSUE TITLE
Litmus post-launch checklist

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/research-force#119]
This is a follow-up to #110 
Please note this list is not set in stone, the entries can be added or modified by demand.

### Crowdloan distribution
- [x] #88 
- [x] #116 
- [x] litentry/litentry-parachain#397
- [x] litentry/litentry-parachain#419
- [x] litentry/research-force#121

### Token bridge
- [x] #118 
- [x] litentry/litentry-parachain#363
- [x] litentry/litentry-parachain#399
- [x] https://github.com/litentry/litentry-parachain/issues/351

### Drop3 & PNS
- [x] #117 
- [x] litentry/litentry-pallets#107
- [x] https://github.com/litentry/litentry-parachain/issues/335
- [x] https://github.com/litentry/litentry-parachain/issues/381

### Documentation
- [x] https://github.com/litentry/litentry-parachain/issues/354

### Devops and Automation
- [x] https://github.com/litentry/litentry-parachain/issues/348
- [x] https://github.com/litentry/litentry-parachain/issues/347
- [x] https://github.com/litentry/litentry-parachain/issues/375
- [x] https://github.com/litentry/litentry-parachain/issues/345
- [x] https://github.com/litentry/litentry-parachain/issues/217
- [x] #81 
- [x] https://github.com/litentry/litentry-parachain/issues/371

### Testing
- [x] https://github.com/litentry/litentry-parachain/issues/356
- [x] https://github.com/litentry/litentry-parachain/issues/340
- [x] https://github.com/litentry/litentry-parachain/issues/346
- [x] https://github.com/litentry/litentry-parachain/issues/312
- [x] https://github.com/litentry/litentry-parachain/issues/330
