### ISSUE TITLE
Kusama parachain launch checklist

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/research-force#21]
## Collator
- [ ] Determine collator mechanism
- [ ] Collation fee
- [ ] Add related pallets to runtime
- [ ] Collator/node Binary/Docker for third party
- [ ] Guide for third party participant collation

## Crowdloan and token distribution
- [ ] Crowdloan details (token release plan, marketing, frontend)
- [ ] Token bridge security confirmation
- [ ] Token bridge integrated into runtime
- [ ] Crowdloan token claim pallet design
- [ ] Add Crowdloan token claim pallet to runtime
- [ ] Collect crowdloan participants

## Runtime
- [ ] Fix pallets and their parameters
- [ ] Add filter for initial runtime pallets
- [ ] Prune our pallets and modify repo structure
- [ ] type.json for frontend
- [ ] Run benchmark

## Genesis
- [ ] Genesis spec

## Tests
- [ ] Runtime upgrade test environment and tests
- [ ] Test in Chachacha or other test relay chain
- [ ] Multi-collator (say 10) test (staging)

## Deployments
- [ ] P2P bootnodes, collators hosted by ourself
- [ ] API services
