### ISSUE TITLE
Parachain launch checklist

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/research-force#23]
## Upstream
- [x] litentry/litentry-parachain#175
- [x] litentry/litentry-parachain#134
- [x] litentry/litentry-parachain#115
- [x]  litentry/litentry-parachain#92 
## Collator
- [x] #14
- [x] #24
- [x] #25
- [x] #26
- [x] litentry/litentry-parachain#93
- [x] #27
- [x] litentry/research-force#51
- [x] litentry/litentry-parachain#105
- [x] litentry/litentry-parachain#79

## Crowdloan and token distribution and 
- [x] Crowdloan details (token release plan, marketing, frontend: out dev)
- [x] #16 
- [x] #58
- [x] litentry/litentry-parachain#155

## Token bridge
- [x] #53
- [x] #55

## Runtime
- [x] #32
- [x] #29 
- [x] #36
- [x] #64
- [x] litentry/litentry-parachain#94
- [x] #30
- [x] litentry/litentry-parachain#165
- [x] check wasm size and PoV block size
- [x] #56

## Genesis
- [x] #75
- [x] #31
- [x] Register to Polkadot with genesis wasm
- [x] #59
- [x] litentry/litentry-parachain#178

## Tests
- [x] litentry/litentry-parachain#95
- [x] #33
- [x] litentry/litentry-parachain#96
- [x] litentry/litentry-parachain#97
- [x] #67

## Deployments
- [x] #34
- [x] #60

## Others
- [x] Go through parachain and substrate launch check list

**Comment by h4n0** [comment]
All the launch preparation-related tickets have been finalized. Other tickets that have to be started after Parachain onboarding have been moved to https://github.com/litentry/research-force/issues/103
This epic is therefore closed.
