### ISSUE TITLE
Parachain post-launch initiatives 

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/research-force#79]
## Higher Priorities
- [x] litentry/litentry-parachain#219

## Fee related
- [ ] Block reward finer research
- [ ] weightToFee and feeMultiplier finer research

## Collator Setup
- [x] litentry/litentry-parachain#218

## On-Chain Data Monitor system
- [ ] Bridge monitor
- [ ] (Abnormal) Balance transfer monitor
  - [x] #84
- [ ] XCM monitor (also on Polkadot)

## Performance Monitor system
- [ ] #89

## Collation
- [ ] Guide and configuration for third party participant collation
